---

name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.30', '5.24' ]
      fail-fast: false
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    env:
      PERL_USE_UNSAFE_INC: 1
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.30"
    - run: cpanm --notest --installdeps .
    - run: cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
    - run: prove -Ilib -lv t
      env:
        HARNESS_PERL_SWITCHES: "-MDevel::Cover=+ignore,inc"
    - run: cover -report coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
