---

name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PERL_USE_UNSAFE_INC: 1
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.30"
    - run: cpanm --notest --installdeps .
    - run: prove -Ilib -lv t